include:
  - compose.proxy.yaml

services:
  dummy-backend:
    environment:
      ACME_HOST: dummy-backend.${HOST_NAME:-rshalimov.duckdns.org}
      VIRTUAL_HOST: dummy-backend.${HOST_NAME:-rshalimov.duckdns.org}
    image: nginxdemos/hello:plain-text

  # first-try:
  #   environment:
  #     ACME_HOST: first-try.${HOST_NAME:-rshalimov.duckdns.org}
  #     VIRTUAL_HOST: first-try.${HOST_NAME:-rshalimov.duckdns.org}
  #     VIRTUAL_PORT: ${PORT:?Port must be specified}
