include:
  - compose.base.yaml

services:
  logitrack:
    build:
      args:
        PNPM_VERSION: ${PNPM_VERSION:?pnpm version must be specified}
      target: dev
    pull_policy: build

    volumes:
      - ./src:/app/src
      - /app/node_modules
