include:
  - compose.proxy.yaml

services:
  dummy-backend:
    environment:
      ACME_HOST: dummy-backend.${HOST_NAME:-rshalimov.duckdns.org}
      VIRTUAL_HOST: dummy-backend.${HOST_NAME:-rshalimov.duckdns.org}
    image: nginxdemos/hello:plain-text

  logitrack:
    environment:
      ACME_HOST: logitrack.${HOST_NAME:-rshalimov.duckdns.org}
      VIRTUAL_HOST: logitrack.${HOST_NAME:-rshalimov.duckdns.org}
      VIRTUAL_PORT: ${PORT:?Port must be specified}
